markdown:           rdiscount
pygments:           true
permalink:          /:year/:month/:day/:title
excerpt_separator:  <!-- more -->
paginate:           6
lsi:                true

name:               Doc
url:                http://jnoee.github.io
ctx:                /doc
description:        这是一个利用 Github + Jekyll + BootStrap 搭建起来的文档博客。
keywords:           文档, Blog, 博客, Github, Jekyll, BootStrap, Liquid
author:             Jnoee